spring.application.name=portafolio
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:petdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# External API
petstore.api.url=https://petstore.swagger.io/v2
